#sample table
assemblies: samples.tsv

#### Pipeline tool dependency files
## dipcall-- choose correct PAR file for reference
#par: "src/dipcall.kit/hs38.PAR.bed"
#par: "src/dipcall.kit/hs37d5.PAR.bed"